export const DESTINATIONS = [
  {
    id: 'skardu',
    name: 'Skardu',
    tagline: 'Lakes, bazaars, and the road to K2',
    description: 'The gateway to eastern Gilgit-Baltistan — turquoise lakes, ancient bazaars, and the road toward Deosai and K2. Most journeys across the region start here.',
    highlights: ['Kachura Lakes', 'Skardu Bazaar', 'Shangrila Resort', 'Gateway to Deosai'],
    colors: ['#1e4976', '#3d8fd1'],
    bestSeason: 'Apr – Oct',
    terrain: 'Highway · 4x4 for Deosai',
  },
  {
    id: 'hunza',
    name: 'Hunza',
    tagline: 'Forts, cherry blossoms, and Karakoram views',
    description: 'From Baltit Fort to Passu’s cathedral spires, Hunza is the valley that defines northern Pakistan — with Attabad Lake, Eagle’s Nest, and the road to Khunjerab Pass.',
    highlights: ['Baltit & Altit Forts', 'Attabad Lake', 'Passu Cones', 'Khunjerab Pass'],
    colors: ['#0d5c4a', '#3cb89a'],
    bestSeason: 'Mar – May · Sep – Oct',
    terrain: 'Karakoram Highway',
  },
  {
    id: 'gilgit',
    name: 'Gilgit',
    tagline: 'Regional capital on the ancient Silk Route',
    description: 'Gilgit city connects Hunza, Nagar, and Skardu by road and air. A practical base with markets, history, and access to Naltar, Fairy Meadows, and the Gilgit River valley.',
    highlights: ['Gilgit Bazaar', 'Kargah Buddha', 'Naltar access', 'Regional transport hub'],
    colors: ['#374151', '#6b7280'],
    bestSeason: 'Apr – Oct',
    terrain: 'Highway · day trips to valleys',
  },
  {
    id: 'deosai',
    name: 'Deosai National Park',
    tagline: 'The roof of the world — open only in summer',
    description: 'One of the highest plateaus on Earth. Wildflowers, brown bears, Sheosar Lake, and skies thick with stars — reached only by 4x4 in season.',
    highlights: ['Sheosar Lake', 'Wildflower meadows', 'Wildlife spotting', 'Stargazing camps'],
    colors: ['#4a3728', '#c4a035'],
    bestSeason: 'Jul – Sep',
    terrain: '4x4 required',
  },
  {
    id: 'khaplu',
    name: 'Khaplu',
    tagline: 'Palaces, apricots, and Ghanche valley calm',
    description: 'In eastern Gilgit-Baltistan, Khaplu Palace and Chaqchan Mosque anchor a valley of orchards, heritage walks, and views toward Masherbrum.',
    highlights: ['Khaplu Palace', 'Chaqchan Mosque', 'Ghanche Valley', 'Heritage trails'],
    colors: ['#5c3d2e', '#d4a574'],
    bestSeason: 'May – Oct',
    terrain: 'Scenic drive from Skardu',
  },
  {
    id: 'shigar',
    name: 'Shigar',
    tagline: 'A restored fort in a quiet orchard valley',
    description: 'Twenty minutes from Skardu, Shigar Fort and its surrounding villages offer slow mornings, heritage architecture, and gentle walks through apricot country.',
    highlights: ['Shigar Fort', 'Amburiq Mosque', 'Apricot orchards', 'Heritage guesthouses'],
    colors: ['#7c4a2d', '#c9956c'],
    bestSeason: 'Apr – Oct',
    terrain: 'Short drive from Skardu',
  },
  {
    id: 'astore',
    name: 'Astore',
    tagline: 'Green valleys on the way to Nanga Parbat',
    description: 'Rolling meadows, pine forests, and the gateway to Rama Lake and Fairy Meadows — Astore is where the Karakoram softens into alpine green.',
    highlights: ['Rama Lake', 'Astore Valley', 'Fairy Meadows route', 'Mountain meadows'],
    colors: ['#2d5016', '#6b8f3c'],
    bestSeason: 'Jun – Sep',
    terrain: 'Highway + jeep tracks',
  },
  {
    id: 'fairy-meadows',
    name: 'Fairy Meadows',
    tagline: 'Camp beneath the face of Nanga Parbat',
    description: 'A legendary campsite at the foot of the world’s ninth-highest peak. Reachable via Raikot Bridge and a jeep track — then a forest hike to the meadow.',
    highlights: ['Nanga Parbat base views', 'Forest trek', 'Alpine camping', 'Sunrise photography'],
    colors: ['#1a4d2e', '#4ade80'],
    bestSeason: 'May – Sep',
    terrain: 'Jeep + trekking',
  },
  {
    id: 'nagar',
    name: 'Nagar',
    tagline: 'Glaciers and peaks across from Hunza',
    description: 'Across the Hunza River, Nagar holds Hopper Glacier, Hispar gateway trails, and quiet villages with uninterrupted views of Rakaposhi and Diran.',
    highlights: ['Hopper Glacier', 'Rakaposhi views', 'Hispar access', 'Traditional villages'],
    colors: ['#1e3a5f', '#5b8db8'],
    bestSeason: 'May – Oct',
    terrain: 'Karakoram side valleys',
  },
  {
    id: 'ghizer',
    name: 'Ghizer & Gupis-Yasin',
    tagline: 'Emerald rivers and off-the-path valleys',
    description: 'Phandar Lake, Gupis, and Yasin Valley — where the Gilgit River runs green and travelers find Gilgit-Baltistan at its most unhurried.',
    highlights: ['Phandar Lake', 'Gupis Valley', 'Yasin Valley', 'Trout fishing'],
    colors: ['#0f766e', '#5eead4'],
    bestSeason: 'May – Oct',
    terrain: 'Highway · optional 4x4 side trips',
  },
  {
    id: 'basho',
    name: 'Basho',
    tagline: 'Meadows and K2-range panoramas',
    description: 'Pine forests open to wildflower meadows with the Karakoram on the horizon — a favourite half-trek from Skardu for those who want altitude without the crowds.',
    highlights: ['Basho Meadows', 'Forest trails', 'K2 range views', 'Day or overnight trek'],
    colors: ['#2d5016', '#a4c639'],
    bestSeason: 'Jun – Sep',
    terrain: '4x4 approach · trekking',
  },
]

export const MARKETPLACE_SERVICES = [
  { id: 'packages', label: 'Curated Packages', desc: 'Ready-made routes across Gilgit-Baltistan', to: '/packages', icon: 'ticket' },
  { id: 'custom', label: 'Build Your Trip', desc: 'Hand-pick stays, rides, and guides', to: '/plan', icon: 'sparkles' },
  { id: 'stays', label: 'Find Your Stay', desc: 'Guesthouses, hostels, and hotels', to: '/explore?tab=stays', icon: 'map' },
  { id: 'transport', label: 'Book Transport', desc: '4x4, jeeps, vans, and private drivers', to: '/explore?tab=transport', icon: 'car' },
  { id: 'guides', label: 'Local Guides', desc: 'Trek, culture, and camping experts', to: '/explore?tab=guides', icon: 'users' },
  { id: 'destinations', label: 'Explore Valleys', desc: 'From Hunza to Deosai and beyond', to: '/destinations', icon: 'mountain' },
]

export const FAQ_ITEMS = [
  {
    q: 'What is GoNorth — and how is it different from a travel agency?',
    a: 'GoNorth is a marketplace built for Gilgit-Baltistan. Local hotels, drivers, and guides list their own services. You see live prices, book with escrow protection, and can start from a curated package or build every detail yourself.',
  },
  {
    q: 'Can I mix valleys on one trip — say Hunza and Skardu?',
    a: 'Absolutely. The trip builder supports multi-leg routes across Gilgit-Baltistan. Add stops, swap stays, change vehicles, and watch your total update in real time.',
  },
  {
    q: 'How does payment work — and when do vendors get paid?',
    a: 'You pay securely at checkout. Funds stay in escrow until your trip is completed and verified, so both you and the local business are protected.',
  },
  {
    q: 'Do I need a 4x4 for Deosai, Basho, or Fairy Meadows?',
    a: 'Deosai and Basho require 4x4 in season. Fairy Meadows is usually jeep-plus-trek. GoNorth flags terrain requirements automatically and filters vehicles that fit your route.',
  },
  {
    q: 'Are the hotels and drivers verified?',
    a: 'Every vendor completes registration and KYC review before going live. Look for solo-safe and women-friendly tags, plus community reviews from past travelers.',
  },
  {
    q: 'What if I need help before or during my trip?',
    a: 'Message vendors in-app, post in the traveler forum, or send a package inquiry. For urgent safety situations, use the SOS button in the header — it works offline and queues until signal returns.',
  },
]
